# Site settings
title: Nigel D'Souza
description: Hit me up if you find anything interesting
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nigeldsouza.io" # the base hostname & protocol for your site
analytics :
  provider : google
  google :
      tracking_id : 'UA-61051773-3'
twitter_username: nigelmd
github_username:  nigelmd

gems:
  - jekyll
  - kramdown
  # - jekyll-watch
  # - redcarpet
  - jekyll-sitemap

# Build settings
markdown: kramdown
